version: '2.3'
services: 
  multiplatform_sample:
    build :
        context : ./app
        dockerfile: Dockerfile   
        args:
          BUILD_IMAGE: stereolabs/iot:0.72.1-devel-jetson-l4t35.1
          RUNTIME_IMAGE: stereolabs/iot:0.72.1-runtime-jetson-l4t35.1
    runtime: nvidia
    environment:
     - MESA_GL_VERSION_OVERRIDE=3.3
    privileged: true
    network_mode: "host"