version: '2.3'
services:
  cam_viewer_service:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: stereolabs/iot:0.72.1-runtime-ubuntu20-cu11.8
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
